name: simulation
channels:
 - conda-forge
 - defaults
 - r
 - bioconda
dependencies:
 - snakemake
 - numpy
 - scikit-learn
 - matplotlib
 - curl=7.45.0
 - bedtools=2.26.0
 - htslib=1.4.1
 - ruby=2.2.2
 - samtools=1.3.1
 - bcftools=1.3.1
